const clinicProfiles = { sabia: { name: 'Clínica Sabiá', unit: 'Unidade Centro', initials: 'CS', user: 'Marina Souza', role: 'Administradora' }, vital: { name: 'Instituto Vital', unit: 'Unidade Jardins', initials: 'IV', user: 'Paulo Mendes', role: 'Gestor financeiro' } };
const activeSession = JSON.parse(localStorage.getItem('tiss-session') || 'null');
const activeClinicId = activeSession?.clinicId || 'sabia';
const clinicStorageKey = key => `tiss-${activeClinicId}-${key}`;
const defaultGuides = [
  { id: 'G-2026-00481', patient: 'Helena Martins', procedure: 'Consulta ambulatorial', insurer: 'Unimed', status: 'approved', label: 'Aprovada', date: '18 ago, 2026', value: 'R$ 180,00' },
  { id: 'G-2026-00480', patient: 'Rafael Nogueira', procedure: 'Sessão de fisioterapia', insurer: 'Bradesco Saúde', status: 'review', label: 'Em análise', date: '18 ago, 2026', value: 'R$ 120,00' },
  { id: 'G-2026-00479', patient: 'Bianca Torres', procedure: 'Ultrassonografia', insurer: 'SulAmérica', status: 'error', label: 'Com pendência', date: '17 ago, 2026', value: 'R$ 260,00' },
  { id: 'G-2026-00478', patient: 'João Pedro Lima', procedure: 'Consulta ambulatorial', insurer: 'Amil', status: 'sent', label: 'Enviada', date: '17 ago, 2026', value: 'R$ 180,00' }
];
let guides = JSON.parse(localStorage.getItem(clinicStorageKey('guides')) || 'null') || defaultGuides;
const defaultAppointments = [
  { id: 'A-001', patient: 'Helena Martins', professional: 'Marina Souza', date: '2026-08-20', start: '09:00', duration: 50, type: 'Consulta' },
  { id: 'A-002', patient: 'Rafael Nogueira', professional: 'Marina Souza', date: '2026-08-20', start: '10:00', duration: 50, type: 'Consulta' },
  { id: 'A-003', patient: 'Bianca Torres', professional: 'Lucas Andrade', date: '2026-08-20', start: '09:30', duration: 60, type: 'Fisioterapia' }
];
let appointments = JSON.parse(localStorage.getItem(clinicStorageKey('appointments')) || 'null') || defaultAppointments;
const views = { overview: 'Visão geral', agenda: 'Agenda', guides: 'Guias TISS', patients: 'Pacientes', convenios: 'Convênios', reports: 'Relatórios', settings: 'Configurações' };
const appView = document.querySelector('#app-view');
const breadcrumb = document.querySelector('#breadcrumb');
const toast = document.querySelector('#toast');

function statusTag(guide) { return `<span class="status ${guide.status}">${guide.label}</span>`; }
function overview() {
  return `<div class="page-heading"><div><p class="eyebrow">Quarta-feira, 19 de agosto de 2026</p><h1>Bom dia, Marina.</h1><p class="heading-copy">Aqui está o pulso do faturamento da sua clínica.</p></div><button class="primary-button" data-action="new-guide">＋ Nova guia</button></div>
  <div class="stats-grid"><article class="stat-card"><div class="stat-top"><span>Guias este mês</span><span class="stat-icon">▣</span></div><div class="stat-value">184</div><div class="stat-note"><b>↑ 12,4%</b> vs. mês anterior</div></article><article class="stat-card"><div class="stat-top"><span>Taxa de aprovação</span><span class="stat-icon">◉</span></div><div class="stat-value">94,8%</div><div class="stat-note"><b>↑ 2,1 p.p.</b> vs. mês anterior</div></article><article class="stat-card"><div class="stat-top"><span>Em análise</span><span class="stat-icon">◷</span></div><div class="stat-value">12</div><div class="stat-note warn"><b>3 vencem hoje</b> precisam de atenção</div></article><article class="stat-card"><div class="stat-top"><span>Valor faturado</span><span class="stat-icon">◇</span></div><div class="stat-value">R$ 42,8k</div><div class="stat-note"><b>↑ 8,7%</b> vs. mês anterior</div></article></div>
  <div class="content-grid"><div class="panel"><div class="panel-header"><div><h2 class="panel-title">Guias recentes</h2><p class="panel-subtitle">Acompanhe as últimas movimentações</p></div><button class="text-button" data-view="guides">Ver todas →</button></div><table><thead><tr><th>Guia</th><th>Paciente</th><th>Convênio</th><th>Status</th><th>Valor</th></tr></thead><tbody>${guides.map(g => `<tr><td><strong>${g.id}</strong><small>${g.date}</small></td><td>${g.patient}<small>${g.procedure}</small></td><td>${g.insurer}</td><td>${statusTag(g)}</td><td><strong>${g.value}</strong></td></tr>`).join('')}</tbody></table></div><div class="panel activity"><div class="panel-header"><div><h2 class="panel-title">Atividade recente</h2><p class="panel-subtitle">Atualizações da operação</p></div></div><div class="activity-item"><span class="activity-dot"></span><div><strong>Guia aprovada</strong><p>G-2026-00481 foi processada pela Unimed</p></div><time>há 18 min</time></div><div class="activity-item"><span class="activity-dot orange"></span><div><strong>Nova pendência</strong><p>G-2026-00479 requer revisão</p></div><time>há 1 h</time></div><div class="activity-item"><span class="activity-dot"></span><div><strong>Lote enviado</strong><p>12 guias enviadas para Bradesco Saúde</p></div><time>há 3 h</time></div></div></div>
  <div class="panel" style="margin-top:18px"><div class="panel-header"><div><h2 class="panel-title">Volume de guias</h2><p class="panel-subtitle">Guias processadas nos últimos 7 dias</p></div><button class="secondary-button">Últimos 7 dias⌄</button></div><div class="chart-area"><div class="chart-grid"><svg class="chart-line" viewBox="0 0 700 140" preserveAspectRatio="none"><polyline points="0,112 100,91 200,101 300,65 400,78 500,34 600,49 700,15"/><circle cx="0" cy="112" r="3"/><circle cx="100" cy="91" r="3"/><circle cx="200" cy="101" r="3"/><circle cx="300" cy="65" r="3"/><circle cx="400" cy="78" r="3"/><circle cx="500" cy="34" r="3"/><circle cx="600" cy="49" r="3"/><circle cx="700" cy="15" r="3"/></svg></div><div class="chart-labels"><span>13 ago</span><span>14 ago</span><span>15 ago</span><span>16 ago</span><span>17 ago</span><span>18 ago</span><span>19 ago</span></div></div></div>`;
}
function guideForm() { return `<div class="page-heading"><div><p class="eyebrow">Nova movimentação</p><h1>Preencher guia TISS</h1><p class="heading-copy">Os dados ficam salvos como rascunho até a validação final.</p></div><button class="secondary-button" data-view="overview">← Voltar</button></div><form class="guide-form" id="guide-form"><div class="form-section"><h2>Dados do atendimento</h2><p>Informe os dados básicos para iniciar a guia.</p><div class="form-grid"><div class="field"><label for="patient">Paciente *</label><input id="patient" required placeholder="Nome completo" /></div><div class="field"><label for="insurer">Convênio *</label><select id="insurer" required><option value="">Selecione o convênio</option><option>Unimed</option><option>Bradesco Saúde</option><option>SulAmérica</option><option>Amil</option></select></div><div class="field"><label for="date">Data do atendimento *</label><input id="date" type="date" required value="2026-08-19" /></div><div class="field"><label for="type">Tipo de atendimento *</label><select id="type" required><option value="">Selecione o tipo</option><option>Consulta</option><option>Exame</option><option>Terapia</option></select></div></div></div><div class="form-section"><h2>Procedimento realizado</h2><p>Busque o procedimento pelo código TUSS ou descrição.</p><div class="form-grid"><div class="field"><label for="procedure">Procedimento *</label><select id="procedure" required><option value="">Selecione o procedimento</option><option>10101012 - Consulta em consultório</option><option>50000470 - Sessão de fisioterapia</option><option>40901122 - Ultrassonografia</option></select></div><div class="field"><label for="professional">Profissional executante *</label><select id="professional" required><option value="">Selecione o profissional</option><option>Marina Souza - CRM 12345</option><option>Lucas Andrade - CREFITO 8812</option></select></div></div></div><div class="form-section"><h2>Conferência</h2><p>A validação automática será executada antes da geração do XML.</p><div class="field"><label for="notes">Observações (opcional)</label><input id="notes" placeholder="Adicione uma observação para o faturamento" /></div></div><div class="form-footer"><button type="button" class="secondary-button" data-action="draft">Salvar rascunho</button><button class="primary-button" type="submit">Validar e continuar →</button></div></form>`; }
function statusSimulator() { return `<div class="panel status-simulator"><div class="panel-header"><div><h2 class="panel-title">Retorno da operadora</h2><p class="panel-subtitle">Simule o processamento para demonstrar o ciclo da guia.</p></div><span class="status sent">Ambiente demo</span></div><div class="status-controls"><select id="status-guide"><option value="">Selecione uma guia</option>${guides.map(guide => `<option value="${guide.id}">${guide.id} · ${guide.patient}</option>`).join('')}</select><button class="status-action review" data-status="review">Em análise</button><button class="status-action approved" data-status="approved">Aprovar</button><button class="status-action error" data-status="error">Glosar</button></div></div>`; }
function guideList() { return `<div class="page-heading"><div><p class="eyebrow">Operação de faturamento</p><h1>Guias TISS</h1><p class="heading-copy">Acompanhe o ciclo de cada guia, do preenchimento ao envio.</p></div><button class="primary-button" data-action="new-guide">＋ Nova guia</button></div><div class="panel"><div class="panel-header"><div><h2 class="panel-title">Todas as guias</h2><p class="panel-subtitle">${guides.length} registros salvos neste navegador</p></div><button class="secondary-button" data-action="clear-guides">Limpar dados demo</button></div><table><thead><tr><th>Guia</th><th>Paciente</th><th>Convênio</th><th>Status</th><th>Valor</th></tr></thead><tbody>${guides.map(g => `<tr><td><strong>${g.id}</strong><small>${g.date}</small></td><td>${g.patient}<small>${g.procedure}</small></td><td>${g.insurer}</td><td>${statusTag(g)}</td><td><strong>${g.value}</strong></td></tr>`).join('')}</tbody></table></div>${statusSimulator()}`; }
function timeToMinutes(time) { const [hours, minutes] = time.split(':').map(Number); return hours * 60 + minutes; }
function hasScheduleConflict(data) { const start = timeToMinutes(data.start); const end = start + Number(data.duration); return appointments.find(appointment => { if (appointment.professional !== data.professional || appointment.date !== data.date) return false; const appointmentStart = timeToMinutes(appointment.start); const appointmentEnd = appointmentStart + Number(appointment.duration); return start < appointmentEnd && end > appointmentStart; }); }
function saveAppointments() { localStorage.setItem(clinicStorageKey('appointments'), JSON.stringify(appointments)); }
function agendaView() { const date = '2026-08-20'; const dayAppointments = appointments.filter(appointment => appointment.date === date).sort((first, second) => timeToMinutes(first.start) - timeToMinutes(second.start)); return `<div class="page-heading"><div><p class="eyebrow">Quinta-feira, 20 de agosto de 2026</p><h1>Agenda da clínica</h1><p class="heading-copy">Horários ocupados são bloqueados automaticamente por profissional.</p></div><button class="primary-button" data-action="new-appointment">＋ Novo atendimento</button></div><div class="agenda-layout"><div class="panel"><div class="panel-header"><div><h2 class="panel-title">Atendimentos de hoje</h2><p class="panel-subtitle">${dayAppointments.length} horários reservados</p></div><span class="status approved">Agenda protegida</span></div><div class="appointment-list">${dayAppointments.map(appointment => `<div class="appointment-row"><div class="appointment-time"><strong>${appointment.start}</strong><small>${appointment.duration} min</small></div><div class="appointment-info"><strong>${appointment.patient}</strong><small>${appointment.type} · ${appointment.professional}</small></div><span class="appointment-professional">${appointment.professional}</span></div>`).join('')}</div></div><form class="panel appointment-form" id="appointment-form"><div class="panel-header"><div><h2 class="panel-title">Reservar horário</h2><p class="panel-subtitle">A checagem acontece antes de salvar.</p></div></div><div class="form-section"><div class="field"><label for="appointment-patient">Paciente *</label><input id="appointment-patient" name="patient" required placeholder="Nome completo" /></div><div class="field"><label for="appointment-professional">Profissional *</label><select id="appointment-professional" name="professional" required><option value="">Selecione</option><option>Marina Souza</option><option>Lucas Andrade</option></select></div><div class="field"><label for="appointment-date">Data *</label><input id="appointment-date" name="date" type="date" value="${date}" required /></div><div class="appointment-fields"><div class="field"><label for="appointment-start">Início *</label><input id="appointment-start" name="start" type="time" value="09:00" required /></div><div class="field"><label for="appointment-duration">Duração *</label><select id="appointment-duration" name="duration" required><option value="30">30 min</option><option value="50" selected>50 min</option><option value="60">60 min</option></select></div></div><div class="field"><label for="appointment-type">Tipo de atendimento *</label><select id="appointment-type" name="type" required><option>Consulta</option><option>Fisioterapia</option><option>Exame</option></select></div></div><div class="form-footer"><button class="primary-button" type="submit">Verificar e reservar</button></div></form></div>`; }
function listing(title, description, icon) { return `<div class="page-heading"><div><p class="eyebrow">Módulo operacional</p><h1>${title}</h1><p class="heading-copy">${description}</p></div><button class="primary-button" data-action="new-guide">＋ Nova guia</button></div><div class="empty-state"><div><div class="empty-icon">${icon}</div><h2>Este módulo está pronto para crescer</h2><p>A estrutura de navegação está funcionando. O próximo passo é conectar este fluxo aos dados reais da clínica.</p><button class="primary-button" data-action="soon">Explorar demonstração</button></div></div>`; }
function saveGuides() { localStorage.setItem(clinicStorageKey('guides'), JSON.stringify(guides)); }
function restoreDraft() { const draft = JSON.parse(localStorage.getItem(clinicStorageKey('draft')) || 'null'); if (!draft) return; Object.entries(draft).forEach(([key, value]) => { const field = document.querySelector(`#${key}`); if (field) field.value = value; }); }
function saveDraft(form) { localStorage.setItem(clinicStorageKey('draft'), JSON.stringify(Object.fromEntries(new FormData(form)))); }
function render(view = 'overview') { breadcrumb.textContent = views[view]; appView.innerHTML = view === 'overview' ? overview() : view === 'agenda' ? agendaView() : view === 'guides' ? guideList() : listing(views[view], `Gerencie ${views[view].toLowerCase()} em um só lugar.`, view === 'patients' ? '◎' : view === 'convenios' ? '◇' : '↗'); }
function applySession() { const clinic = clinicProfiles[activeClinicId]; if (!clinic) return; document.querySelector('.workspace-switcher strong').textContent = clinic.name; document.querySelector('.workspace-switcher small').textContent = clinic.unit; document.querySelector('.workspace-switcher .avatar').textContent = clinic.initials; document.querySelector('.profile strong').textContent = clinic.user; document.querySelector('.profile small').textContent = clinic.role; document.querySelector('.user-button span:nth-child(2)').textContent = clinic.user; document.querySelector('.user-button .avatar').textContent = clinic.user.split(' ').map(name => name[0]).join(''); }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
function escapeXml(value) {
  return String(value).replace(/[<>&'\"]/g, character => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '\"': '&quot;' }[character]));
}
function createTissXml(data) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<mensagemTISS versao="4.01.00">
  <cabecalho><identificacaoTransacao><tipoTransacao>ENVIO_LOTE_GUIAS</tipoTransacao><sequencialTransacao>000001</sequencialTransacao><dataRegistroTransacao>${data.date}</dataRegistroTransacao><horaRegistroTransacao>10:30:00</horaRegistroTransacao></identificacaoTransacao></cabecalho>
  <prestador><identificacao><CNPJ>12.345.678/0001-90</CNPJ></identificacao><nomeContratado>Clinica Sabia</nomeContratado></prestador>
  <guiasTISS><guiaSP_SADT><cabecalhoGuia><registroANS>000000</registroANS><numeroGuiaPrestador>G-2026-DEMO</numeroGuiaPrestador></cabecalhoGuia><dadosAutorizacao><numeroGuiaOperadora>NAO_INFORMADO</numeroGuiaOperadora></dadosAutorizacao><beneficiario><numeroCarteira>${escapeXml(data.insurer)}-DEMO</numeroCarteira><nomeBeneficiario>${escapeXml(data.patient)}</nomeBeneficiario></beneficiario><dadosAtendimento><dataAtendimento>${data.date}</dataAtendimento><tipoAtendimento>${escapeXml(data.type)}</tipoAtendimento><procedimento>${escapeXml(data.procedure)}</procedimento><profissional>${escapeXml(data.professional)}</profissional></dadosAtendimento><observacao>${escapeXml(data.notes || '')}</observacao></guiaSP_SADT></guiasTISS>
</mensagemTISS>`;
}
function downloadXml(xml) {
  const blob = new Blob([xml], { type: 'application/xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'guia-tiss-demo.xml';
  link.click();
  URL.revokeObjectURL(url);
}
document.addEventListener('click', event => { const viewButton = event.target.closest('[data-view]'); if (viewButton) { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === viewButton.dataset.view)); render(viewButton.dataset.view); } const statusButton = event.target.closest('[data-status]'); if (statusButton) { const guideId = document.querySelector('#status-guide')?.value; if (!guideId) { showToast('Selecione uma guia antes de registrar o retorno.'); return; } const statusLabels = { review: 'Em análise', approved: 'Aprovada', error: 'Glosada' }; const guide = guides.find(item => item.id === guideId); guide.status = statusButton.dataset.status; guide.label = statusLabels[guide.status]; saveGuides(); render('guides'); showToast(`Retorno registrado: ${guide.label}.`); } const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'logout') { localStorage.removeItem('tiss-session'); window.location.reload(); } if (action === 'new-guide') { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === 'guides')); breadcrumb.textContent = 'Nova guia'; appView.innerHTML = guideForm(); restoreDraft(); } if (action === 'new-appointment') { breadcrumb.textContent = 'Novo atendimento'; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === 'agenda')); appView.innerHTML = agendaView(); document.querySelector('#appointment-patient')?.focus(); } if (action === 'clear-guides') { guides = [...defaultGuides]; saveGuides(); render('guides'); showToast('Dados demo restaurados.'); } if (action === 'soon') showToast('Demonstração em preparação.'); });
document.addEventListener('submit', event => { if (event.target.id === 'login-form') { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); if (data.password.length < 4) return; localStorage.setItem('tiss-session', JSON.stringify({ clinicId: data.clinicId, email: data.email })); window.location.reload(); return; } if (event.target.id === 'appointment-form') { event.preventDefault(); const form = event.target; if (!form.checkValidity()) { form.reportValidity(); return; } const data = Object.fromEntries(new FormData(form)); const conflict = hasScheduleConflict(data); if (conflict) { showToast(`Conflito: ${conflict.professional} já atende ${conflict.patient} às ${conflict.start}.`); return; } appointments.push({ id: `A-${String(appointments.length + 1).padStart(3, '0')}`, ...data, duration: Number(data.duration) }); saveAppointments(); render('agenda'); showToast('Horário reservado sem conflito.'); return; } if (event.target.id !== 'guide-form') return; event.preventDefault(); const form = event.target; if (!form.checkValidity()) { form.reportValidity(); return; } const data = Object.fromEntries(new FormData(form)); const xml = createTissXml(data); guides.unshift({ id: `G-2026-${String(guides.length + 482).padStart(5, '0')}`, patient: data.patient, procedure: data.procedure.split(' - ')[1] || data.procedure, insurer: data.insurer, status: 'sent', label: 'Pronta para envio', date: '19 ago, 2026', value: 'A definir' }); saveGuides(); localStorage.removeItem(clinicStorageKey('draft')); downloadXml(xml); showToast('Guia validada, salva e XML baixado.'); });
if (activeSession) { document.querySelector('#login-screen').classList.add('hidden'); applySession(); } else { document.querySelector('.app-shell').classList.add('hidden'); }
render();
